version: '3.8'

services:
  system-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: student_performance_system
    ports:
      - "8000:8000"
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
